name: MLHB
channels: 
  - defaults
  - conda-forge 
  - imperial-college-research-computing
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - tqdm
  - pylogit
  - pip:
    - biogeme
    - xlogit
