name: MLHB
channels: 
  - defaults
  - conda-forge 
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - tqdm
  - pylogit
